### PR TITLE
docs on install prefix and the use of pkg-config

### PR DESCRIPTION
**Pull request by dimpase**
this is basically #112, but onto stable-0.6 branch

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
The CI ought to pass if this is rebased onto the current head of stable-0.6. Thanks @dimpase !

**Comment by dimpase** [comment]
Well, one of the 9 runs on Travis fails due to trying to test libsemigroups from a git-cloned version of GAP's semigroup, and this does not work as the latter does want to see a copy of libsemigroup in the directory. Looks like you don't manage to pass it `--with-external-libsemigroups`.

**Comment by james-d-mitchell** [comment]
I fixed the fail Travis test in a pr which I merged some hours ago, if you rebase it will pass.

**Comment by dimpase** [comment]
Thanks - I was to start rebasing soon :-)

**Comment by dimpase** [comment]
I'll do a PR on Semigroups with documentation referring to this documentation.

**Comment by james-d-mitchell** [comment]
Sounds good, I should be able to release Semigroups and libsemigroups new versions today.

**Pull request merged**
